//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegurosSigloXXl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdiccionesEncabezado
    {
        public AdiccionesEncabezado()
        {
            this.AdiccionesDetalle = new HashSet<AdiccionesDetalle>();
        }
    
        public int IdAdiccionCliente { get; set; }
        public int IdCliente { get; set; }
        public int TotalAdicciones { get; set; }
    
        public virtual ICollection<AdiccionesDetalle> AdiccionesDetalle { get; set; }
    }
}
