//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegurosSigloXXl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdiccionesDetalle
    {
        public int IdAdiccionDetalle { get; set; }
        public int IdAdiccionCliente { get; set; }
        public int IdAdiccion { get; set; }
    
        public virtual Adicciones Adicciones { get; set; }
        public virtual AdiccionesEncabezado AdiccionesEncabezado { get; set; }
    }
}
