//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegurosSigloXXl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroPoliza
    {
        public int IdRegistroPoliza { get; set; }
        public int IdCoberturaPoliza { get; set; }
        public int IdCliente { get; set; }
        public float MontoAsegurado { get; set; }
        public float PorcentajeCobertura { get; set; }
        public float MontoAdicciones { get; set; }
        public float PrimaAntesImpuesto { get; set; }
        public float Impuesto { get; set; }
        public float PrimaFinal { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual CoberturaPoliza CoberturaPoliza { get; set; }
    }
}
